/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.util.ArrayList;
import java.util.Scanner;

public class App {

    public static boolean appRun = true;

    public static void main(String[] args) {
        
        Scanner scanner = new Scanner(System.in);
        

        while(appRun){
            ArrayList<TrackedCat> allTrackedCats = DAL.getTrackedCats();

            System.out.println("\n---Tracked--Study--Cats------------------------------------");

            for(TrackedCat studyCat : allTrackedCats){
                if(studyCat.reviewTick < 12){
                    System.out.println(studyCat.getTrackedCat());
                }
            }
            System.out.println("-----------------------------------------------------------\n");

            System.out.println("enter 'A' to add new tracked study cat");
            System.out.println("enter 'R' to remove a study cat from tracking list");
            System.out.println("enter 'T' to increase review tick (you just studied something)");
            String heroChoice = scanner.nextLine();

            switch (heroChoice.toUpperCase().strip()){
                case "A" -> newTrackedCat(scanner);
                case "R" -> minusTrackedCat(scanner);
                case "T" -> increaseReviewTick(scanner);
                default -> System.out.println("Invalid choice.\n");
            }
        }

        scanner.close();
    }

    public static void newTrackedCat(Scanner scanner){
        System.out.print("Enter the name of the newly tracked Study Cat: ");
        String newTrackedCat = scanner.nextLine().strip();
        DAL.addTrackedCat(newTrackedCat);
    }

    public static void minusTrackedCat(Scanner scanner){
        System.out.println("Enter the name of the study cat you'd like to stop tracking: ");
         String removedCat = scanner.nextLine().strip();
         DAL.removeTrackedCat(removedCat, scanner);
    }

    public static void increaseReviewTick(Scanner scanner){
        System.out.println("Enter the name of the study cat you just reviewd: ");
        String reviewedCat = scanner.nextLine().strip();
        DAL.reviewedTrackedCat(reviewedCat, scanner);
    }
}
